const String Base_URL = 'https://j03ps88p-5000.asse.devtunnels.ms/';
const String Login_Endpoint = 'api/auth/login';
const String Register_Endpoint = 'api/auth/signup';
const String Parent_Report_Create = 'api/reports/parent';
const String Parent_Report_My = 'api/reports/parent/my';
const String Parent_Report_By_Id = 'api/reports/parent'; // Append /{reportId}
const String Finder_Report_Create = 'api/reports/finder';
const String Finder_Report_My = 'api/reports/finder/my';
const String Finder_Report_By_Id = 'api/reports/finder'; // Append /{reportId}