name: locat_lost
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^1.2.1
  dotted_border: ^2.1.0
  flutter_svg: ^2.1.0
  camera: ^0.11.1
  path: ^1.9.1
  path_provider: ^2.1.5
  fl_chart: ^0.71.0
  charts_flutter: ^0.12.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
#    - assets/login.jpg
#    - assets/report.png
#    - assets/unlink.png
#    - assets/link.png
#    - assets/link-03.png
#    - assets/zulfi.png
#    - assets/splash1.png
#    - assets/splash2.png
#    - assets/splash3.png
#    - assets/ali.png
#    - assets/zulfiqar.png
#    - assets/bg.png
#    - assets/bgg.png
#    - assets/Map1.svg
#    - assets/Map2.svg
#    - assets/Map2.svg
